import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerWrapper: {
    position: 'relative',
    marginBottom: 12,
  },
  card: {
    borderRadius: 20,
    padding: 16,
    position: 'relative',
  },
  pinBadge: {
    position: 'absolute',
    top: -6,
    right: 16,
    backgroundColor: '#18181B',
    borderRadius: 11,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
    elevation: 4,
  },
  deleteActionBox: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 65,
    borderRadius: 20,
    overflow: 'hidden',
  },
  deleteButtonInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  infoCol: {
    flex: 1,
    justifyContent: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  spaceName: {
    fontSize: 17,
    fontFamily: 'Poppins_700Bold',
    color: '#111111',
    letterSpacing: -0.3,
  },
  tagline: {
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
    color: '#555555',
    lineHeight: 16,
  },
  memberStack: {
    marginLeft: 8,
  },
  memberText: {
    fontSize: 12,
    fontFamily: 'Poppins_500Medium',
    color: '#444444',
  },
  contextFooter: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  contextLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  contextDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#111111',
    marginRight: 6,
  },
  contextText: {
    fontSize: 12,
    fontFamily: 'Poppins_500Medium',
    color: '#222222',
    flex: 1,
  },
  timeText: {
    fontSize: 11,
    fontFamily: 'Poppins_400Regular',
    color: '#666666',
    marginLeft: 8,
  },
});
