import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 16,
    paddingBottom: 14,
    marginBottom: 24,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    position: 'relative',
    overflow: 'hidden',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
  },
  accentDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  badgeText: {
    fontSize: 10,
    fontFamily: 'Poppins_600SemiBold',
    letterSpacing: 0.6,
  },
  mainContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 14,
  },
  calendarBlock: {
    width: 56,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
    alignItems: 'center',
  },
  calendarMonthHeader: {
    width: '100%',
    paddingVertical: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: 'Poppins_700Bold',
    letterSpacing: 0.8,
  },
  calendarDayBody: {
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDayNumber: {
    fontSize: 18,
    fontFamily: 'Poppins_700Bold',
    lineHeight: 22,
  },
  calendarWeekdayText: {
    fontSize: 8.5,
    fontFamily: 'Poppins_600SemiBold',
    color: '#8E8D94',
    marginTop: -2,
    letterSpacing: 0.3,
  },
  planInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  detailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detailText: {
    fontSize: 12.5,
    color: '#8E8D94',
    fontFamily: 'Poppins_500Medium',
  },
  footerDivider: {
    height: 1,
    width: '100%',
    marginBottom: 10,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  attendanceText: {
    fontSize: 12,
    color: '#71717A',
    fontFamily: 'Poppins_500Medium',
  },
  emptyCard: {
    borderRadius: 24,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    padding: 24,
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 16,
    marginBottom: 2,
  },
  emptySubtitle: {
    color: '#8E8D94',
    fontSize: 13,
    marginBottom: 14,
  },
  addPlanBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addPlanText: {
    fontSize: 12,
    fontFamily: 'Poppins_600SemiBold',
  },
});
